/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-11-10 13:49:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.web.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class productDetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/oOOo/Desktop/HKII_21_22/java/ecom/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/com.comestic/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
    _jspx_dependants.put("/common/taglib.jsp", Long.valueOf(1667542579247L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1661705607620L));
    _jspx_dependants.put("jar:file:/C:/Users/oOOo/Desktop/HKII_21_22/java/ecom/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/com.comestic/WEB-INF/lib/sitemesh-2.4.2.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1123653092000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.4.2.jar", Long.valueOf(1662091751547L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("	<title>Chi tiết sản phẩm</title>\r\n");
      out.write("	<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" 	<div class=\"body\" id=\"contain\">\r\n");
      out.write("        	<div class=\"grid wide\">\r\n");
      out.write("        		<div class=\"directory\">\r\n");
      out.write("					<span class=\"directory_text category\"><!-- Điện thoại --></span>\r\n");
      out.write("					<span class=\"directory_icon\">\r\n");
      out.write("						<i class=\"fa-solid fa-chevron-right\"></i>\r\n");
      out.write("					</span>\r\n");
      out.write("					<span class=\"directory_text product\"><!-- Điện thoại Redmi --></span>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"productInfo\">\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("                        <div class=\"col p-12 t-12 m-12\">\r\n");
      out.write("                            <div class=\"product__intro\">\r\n");
      out.write("                                <span class=\"name\"><!-- Điện thoại Redmi XYZ 123 --></span>\r\n");
      out.write("                                <span class=\"stars\">\r\n");
      out.write("\r\n");
      out.write("                                </span>\r\n");
      out.write("                                <span class=\"num_review\"><!-- 20 đánh giá --></span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col p-7 t-12 m-12\">\r\n");
      out.write("							<div class=\"images\">\r\n");
      out.write("                                <div class=\"img_show\" \r\n");
      out.write("                                     style=\"background-image: url();\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"all_text\">\r\n");
      out.write("                                    <!-- Tất cả hình ảnh (1/3) -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"imgs\">\r\n");
      out.write("                                    <!-- active: .active -->\r\n");
      out.write("                                    <!-- <img class=\"img_other active\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("                                    <img class=\"img_other\" src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\">\r\n");
      out.write("                                    <img class=\"img_other\" src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\"> -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"col p-5 t-12 m-12\">\r\n");
      out.write("							<div class=\"info\">\r\n");
      out.write("								<div class=\"styles\">\r\n");
      out.write("                                    <div class=\"style__select__contain\">\r\n");
      out.write("    									\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"price\">\r\n");
      out.write("										<span class=\"price__text\">Giá: </span>\r\n");
      out.write("										<span class=\"price__num\"><!-- 2.600.000đ --></span>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"state\">\r\n");
      out.write("                                        <span class=\"state__text\">Trạng thái: </span>\r\n");
      out.write("                                        <span class=\"state__value\">Còn hàng</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Hide: .hide -->\r\n");
      out.write("									<div class=\"info__detail\">\r\n");
      out.write("										<p class=\"info__detail__text\">Thông tin chi tiết</p>\r\n");
      out.write("										<div class=\"info__detail__describe\">\r\n");
      out.write("											<p>RAM: 2GB</p>\r\n");
      out.write("											<p>Bộ nhớ: 16GB</p>\r\n");
      out.write("											<p>Pin: 20000 mA</p>\r\n");
      out.write("											<p>Hãng sản xuất: Samsung</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"number\">\r\n");
      out.write("                                        <p class=\"number__text\">Số lượng: </p>\r\n");
      out.write("                                        <span class=\"number_item sub\">-</span>\r\n");
      out.write("                                        <span class=\"number_item value\">\r\n");
      out.write("                                            <input class=\"number__input\" type=\"text\" value=\"1\">\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        <span class=\"number_item plus\">+</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"row\">\r\n");
      out.write("                                        <div class=\"col p-6 t-6 m-12\"> \r\n");
      out.write("                                            <button id=\"addtocart\">Thêm vào giỏ hàng</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col p-6 t-6 m-12\">\r\n");
      out.write("                                            <button id=\"buynow\">Mua sản phẩm ngay</button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("									</div>\r\n");
      out.write("									\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Popup: .popup, No information: .hide -->\r\n");
      out.write("                <div class=\"describe__contain\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col p-7 t-12 m-12\">\r\n");
      out.write("                            <div class=\"describe__detail\">\r\n");
      out.write("                                <div class=\"describe__detail__header\">Thông tin sản phẩm</div>\r\n");
      out.write("                                <div class=\"describe__detail__content\">\r\n");
      out.write("                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("                                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("                                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("                                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("                                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n");
      out.write("\r\n");
      out.write("                                    <img src=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("\" style=\"width:100%\">\r\n");
      out.write("\r\n");
      out.write("                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("                                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("                                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("                                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("                                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n");
      out.write("\r\n");
      out.write("                                    <img src=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("\" style=\"width:100%\">\r\n");
      out.write("\r\n");
      out.write("                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod\r\n");
      out.write("                                    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,\r\n");
      out.write("                                    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo\r\n");
      out.write("                                    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse\r\n");
      out.write("                                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non\r\n");
      out.write("                                    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"describe__detail__viewmore hide\">\r\n");
      out.write("                                    <button>\r\n");
      out.write("                                        <span>Xem thêm</span>\r\n");
      out.write("                                        <i class=\"fa-solid fa-caret-down\"></i>\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"describe__detail__close\">Đóng</div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col p-7 t-12 m-12\">\r\n");
      out.write("                        <!-- no review: .no-review -->\r\n");
      out.write("                        <div class=\"review__detail\">\r\n");
      out.write("                            <p class=\"review__detail__header\">Đánh giá điện thoại Nokia A1202</p>\r\n");
      out.write("                            <div class=\"review__detail__stardetail\">\r\n");
      out.write("                                <div class=\"star__total\">\r\n");
      out.write("                                    <span class=\"star__total__number\">3.7</span>\r\n");
      out.write("                                    <span class=\"star__total__icon\">\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <span class=\"star__total__review\">48 đánh giá</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"star__number__list\">\r\n");
      out.write("                                    <div class=\"star__number__item\">\r\n");
      out.write("                                        <div class=\"star__number__quantity\">\r\n");
      out.write("                                            <span>5</span>\r\n");
      out.write("                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__range\">\r\n");
      out.write("                                            <div style=\"--percent:40%;\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__percent\">40%</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"star__number__item\">\r\n");
      out.write("                                        <div class=\"star__number__quantity\">\r\n");
      out.write("                                            <span>4</span>\r\n");
      out.write("                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__range\">\r\n");
      out.write("                                            <div style=\"--percent:30%;\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__percent\">30%</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"star__number__item\">\r\n");
      out.write("                                        <div class=\"star__number__quantity\">\r\n");
      out.write("                                            <span>3</span>\r\n");
      out.write("                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__range\">\r\n");
      out.write("                                            <div style=\"--percent:20%;\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__percent\">20%</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"star__number__item\">\r\n");
      out.write("                                        <div class=\"star__number__quantity\">\r\n");
      out.write("                                            <span>2</span>\r\n");
      out.write("                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__range\">\r\n");
      out.write("                                            <div style=\"--percent:10%;\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__percent\">10%</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"star__number__item\">\r\n");
      out.write("                                        <div class=\"star__number__quantity\">\r\n");
      out.write("                                            <span>1</span>\r\n");
      out.write("                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__range\">\r\n");
      out.write("                                            <div style=\"--percent:0%;\"></div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"star__number__percent\">0%</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"review__detail__list\">\r\n");
      out.write("                                <!-- Max Item: 2 -->\r\n");
      out.write("                                <div class=\"review__detail__item\">\r\n");
      out.write("                                    <span class=\"review__item__name\">Võ Nguyên Giáp</span>\r\n");
      out.write("                                    <div class=\"review__item__starnum\">\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"review__item__content\">Sản phẩm khá là tốt, sẽ giới thiệu cho nhiều người!</div>\r\n");
      out.write("                                    <div class=\"review__item__time\">7 phút trước</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"review__detail__item\">\r\n");
      out.write("                                    <span class=\"review__item__name\">Sống ảo</span>\r\n");
      out.write("                                    <div class=\"review__item__starnum\">\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"review__item__content\">Sản phẩm khá là tốt, sẽ giới thiệu cho nhiều người!</div>\r\n");
      out.write("                                    <div class=\"review__item__time\">7 phút trước</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"review__detail__item\">\r\n");
      out.write("                                    <span class=\"review__item__name\">Nguyễn Văn Anh</span>\r\n");
      out.write("                                    <div class=\"review__item__starnum\">\r\n");
      out.write("                                       <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                        <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"review__item__content\">Sản phẩm khá là tốt, sẽ giới thiệu cho nhiều người!</div>\r\n");
      out.write("                                    <div class=\"review__item__time\">7 phút trước</div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"review__detail__no-review\">Hiện không có đánh giá cho sản phẩm!</div>\r\n");
      out.write("                            <div class=\"review__detail__option\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col p-6 t-6 m-12\">\r\n");
      out.write("                                        <div class=\"review__writenew\">Viết đánh giá</div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col p-6 t-6 m-12\">\r\n");
      out.write("                                        <!-- hide: .hide -->\r\n");
      out.write("                                        <div class=\"review__detail__viewmore\">\r\n");
      out.write("                                            <span>Xem thêm đánh 20 giá</span>\r\n");
      out.write("                                            <i class=\"fa-solid fa-caret-down\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <!-- Display popup: .popup -->\r\n");
      out.write("                        <div class=\"write__review__contain\">\r\n");
      out.write("                            <div class=\"grid wide\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col p-5 t-8 m-12\">\r\n");
      out.write("                                        <div class=\"write__review\">\r\n");
      out.write("                                            <div class=\"write__review__header\">\r\n");
      out.write("                                                <span class=\"write__review__text\">Đánh giá</span>\r\n");
      out.write("                                                <span class=\"write__review__close\">\r\n");
      out.write("                                                    <i class=\"fa-solid fa-xmark\"></i>\r\n");
      out.write("                                                </span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"write__review__body\">\r\n");
      out.write("                                                <div class=\"write__review__star\">\r\n");
      out.write("                                                    <!-- Select .select, UserClick: .userselect -->\r\n");
      out.write("                                                    <div class=\"write__review__starselect select\">\r\n");
      out.write("                                                        <span class=\"review__star__select\">\r\n");
      out.write("                                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__unselect\">\r\n");
      out.write("                                                            <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__text\">Rất tệ</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"write__review__starselect select\">\r\n");
      out.write("                                                        <span class=\"review__star__select\">\r\n");
      out.write("                                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__unselect\">\r\n");
      out.write("                                                            <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__text\">Tệ</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"write__review__starselect select userselect\">\r\n");
      out.write("                                                        <span class=\"review__star__select\">\r\n");
      out.write("                                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__unselect\">\r\n");
      out.write("                                                            <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__text\">Bình thường</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"write__review__starselect\">\r\n");
      out.write("                                                        <span class=\"review__star__select\">\r\n");
      out.write("                                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__unselect\">\r\n");
      out.write("                                                            <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__text\">Tốt</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"write__review__starselect\">\r\n");
      out.write("                                                        <span class=\"review__star__select\">\r\n");
      out.write("                                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__unselect\">\r\n");
      out.write("                                                            <i class=\"fa-regular fa-star\"></i>\r\n");
      out.write("                                                        </span>\r\n");
      out.write("                                                        <span class=\"review__star__text\">Rất tốt</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"write__review__content\">\r\n");
      out.write("                                                    <div class=\"formGroupt\" id=\"write__review__text\">\r\n");
      out.write("                                                        <textarea placeholder=\"Mời bạn để lại đánh giá...\"></textarea>\r\n");
      out.write("                                                        <span class=\"form-message\">Trường này không thể bỏ trống!</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"formGroupt\">\r\n");
      out.write("                                                        <input type=\"text\" placeholder=\"Họ và tên\">\r\n");
      out.write("                                                        <span class=\"form-message\">Trường này không thể bỏ trống!</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"formGroupt\">\r\n");
      out.write("                                                        <input type=\"text\" placeholder=\"Email\">\r\n");
      out.write("                                                        <span class=\"form-message\">Trường này không thể bỏ trống!</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"formGroupt\">\r\n");
      out.write("                                                        <input type=\"number\" placeholder=\"Số điện thoại\">\r\n");
      out.write("                                                        <span class=\"form-message\">Trường này không thể bỏ trống!</span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                \r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"write__review__send\">Gửi đánh giá</div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Product relative -->\r\n");
      out.write("				<div class=\"product_relative\">\r\n");
      out.write("					<div class=\"product_relative_text\">\r\n");
      out.write("						Sản phẩm có liên quan\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"row\">\r\n");
      out.write("                        <div class=\"col p-2-4 t-4 m-6\">\r\n");
      out.write("                            <div class=\"product__item sale\">\r\n");
      out.write("                                <div class=\"product__image\" \r\n");
      out.write("                                     style=\"background-image: url(");
      if (_jspx_meth_c_005furl_005f6(_jspx_page_context))
        return;
      out.write(");\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"product__info\">\r\n");
      out.write("                                    <span class=\"product__supply\">Samsung</span>\r\n");
      out.write("                                    <div class=\"product__name\">Điện thoại Samsung A2 104</div>\r\n");
      out.write("                                    <div class=\"product__price\">\r\n");
      out.write("                                        <span class=\"price__sold\">2.000.000đ</span>\r\n");
      out.write("                                        <span class=\"percent\">Giảm 20%</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"product__review\">\r\n");
      out.write("                                        <span class=\"product__star__num\">4.6</span>\r\n");
      out.write("                                        <span class=\"product__star__icon\">\r\n");
      out.write("                                            <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                        <span class=\"product__number__comment\">(22)</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col p-2-4 t-4 m-6\">\r\n");
      out.write("                                        <div class=\"product__item sale\">\r\n");
      out.write("                                            <div class=\"product__image\" \r\n");
      out.write("                                                 style=\"background-image: url(");
      if (_jspx_meth_c_005furl_005f7(_jspx_page_context))
        return;
      out.write(");\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__info\">\r\n");
      out.write("                                                <span class=\"product__supply\">Samsung</span>\r\n");
      out.write("                                                <div class=\"product__name\">Điện thoại Samsung A2 104</div>\r\n");
      out.write("                                                <div class=\"product__price\">\r\n");
      out.write("                                                    <span class=\"price__sold\">2.000.000đ</span>\r\n");
      out.write("                                                    <span class=\"percent\">Giảm 20%</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"product__review\">\r\n");
      out.write("                                                    <span class=\"product__star__num\">4.6</span>\r\n");
      out.write("                                                    <span class=\"product__star__icon\">\r\n");
      out.write("                                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                    <span class=\"product__number__comment\">(22)</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col p-2-4 t-4 m-6\">\r\n");
      out.write("                                        <div class=\"product__item\">\r\n");
      out.write("                                            <div class=\"product__image\" \r\n");
      out.write("                                                 style=\"background-image: url(");
      if (_jspx_meth_c_005furl_005f8(_jspx_page_context))
        return;
      out.write(");\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__info\">\r\n");
      out.write("                                                <span class=\"product__supply\">Samsung</span>\r\n");
      out.write("                                                <div class=\"product__name\">Điện thoại Samsung A2 104</div>\r\n");
      out.write("                                                <div class=\"product__price\">\r\n");
      out.write("                                                    <span class=\"price__sold\">2.000.000đ</span>\r\n");
      out.write("                                                    <span class=\"percent\">Giảm 20%</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"product__review\">\r\n");
      out.write("                                                    <span class=\"product__star__num\">4.6</span>\r\n");
      out.write("                                                    <span class=\"product__star__icon\">\r\n");
      out.write("                                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                    <span class=\"product__number__comment\">(22)</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col p-2-4 t-4 m-6\">\r\n");
      out.write("                                        <div class=\"product__item\">\r\n");
      out.write("                                            <div class=\"product__image\" \r\n");
      out.write("                                                 style=\"background-image: url(");
      if (_jspx_meth_c_005furl_005f9(_jspx_page_context))
        return;
      out.write(");\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__info\">\r\n");
      out.write("                                                <span class=\"product__supply\">Samsung</span>\r\n");
      out.write("                                                <div class=\"product__name\">Điện thoại Samsung A2 104</div>\r\n");
      out.write("                                                <div class=\"product__price\">\r\n");
      out.write("                                                    <span class=\"price__sold\">2.000.000đ</span>\r\n");
      out.write("                                                    <span class=\"percent\">Giảm 20%</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"product__review\">\r\n");
      out.write("                                                    <span class=\"product__star__num\">4.6</span>\r\n");
      out.write("                                                    <span class=\"product__star__icon\">\r\n");
      out.write("                                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                    <span class=\"product__number__comment\">(22)</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col p-2-4 t-4 m-6\">\r\n");
      out.write("                                        <div class=\"product__item\">\r\n");
      out.write("                                            <div class=\"product__image\" \r\n");
      out.write("                                                 style=\"background-image: url(");
      if (_jspx_meth_c_005furl_005f10(_jspx_page_context))
        return;
      out.write(");\">\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                            <div class=\"product__info\">\r\n");
      out.write("                                                <span class=\"product__supply\">Samsung</span>\r\n");
      out.write("                                                <div class=\"product__name\">Điện thoại Samsung A2 104</div>\r\n");
      out.write("                                                <div class=\"product__price\">\r\n");
      out.write("                                                    <span class=\"price__sold\">2.000.000đ</span>\r\n");
      out.write("                                                    <span class=\"percent\">Giảm 20%</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"product__review\">\r\n");
      out.write("                                                    <span class=\"product__star__num\">4.6</span>\r\n");
      out.write("                                                    <span class=\"product__star__icon\">\r\n");
      out.write("                                                        <i class=\"fa-solid fa-star\"></i>\r\n");
      out.write("                                                    </span>\r\n");
      out.write("                                                    <span class=\"product__number__comment\">(22)</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("                <!-- Comment -->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <div class=\"col p-12 t-12 m-12\">\r\n");
      out.write("                        <!-- No comment: .no-comment -->\r\n");
      out.write("                        <div class=\"comment\">\r\n");
      out.write("                            <p class=\"comment__header__text\">Bình luận sản phẩm</p>\r\n");
      out.write("                            <div class=\"comment__header\">\r\n");
      out.write("                                <textarea class=\"comment__text__edit\" placeholder=\"Nhập bình luận...\"></textarea>\r\n");
      out.write("                                <div class=\"comment__send\">\r\n");
      out.write("                                    <button>Gửi bình luận</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <!-- Active: .active -->\r\n");
      out.write("                                <div class=\"comment__information__contain\">\r\n");
      out.write("                                    <div class=\"grid wide\">\r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"col p-5 t-8 m-12\">\r\n");
      out.write("                                                <div class=\"comment__information\">\r\n");
      out.write("                                                    <div class=\"comment__information__header\">\r\n");
      out.write("                                                        <span class=\"comment__information__text\">Thông tin người gửi</span>\r\n");
      out.write("                                                        <span class=\"comment__information__close\"><i class=\"fa-solid fa-xmark\"></i></span>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"comment__information__body\">\r\n");
      out.write("                                                        <div class=\"formGroupt\" id=\"fullname\">\r\n");
      out.write("                                                            <input type=\"text\" placeholder=\"Nhập họ tên\">\r\n");
      out.write("                                                            <!-- Error: .error -->\r\n");
      out.write("                                                            <span class=\"form-message\">Trường này không thể bỏ trống!</span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"formGroupt\" id=\"email\">\r\n");
      out.write("                                                            <input type=\"text\" placeholder=\"Nhập email\">\r\n");
      out.write("                                                            <span class=\"form-message\">Trường này không thể bỏ trống!</span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"formGroupt\" id=\"phone\">\r\n");
      out.write("                                                            <input type=\"number\" placeholder=\"Nhập số điện thoại\">\r\n");
      out.write("                                                            <span class=\"form-message\">Trường này không thể bỏ trống!</span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"comment__information__send\">Gửi bình luận</div>\r\n");
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"comment__body\">\r\n");
      out.write("                                <p class=\"comment__body__text\">Có 100 bình luận</p>\r\n");
      out.write("                                <div class=\"comment__list\">\r\n");
      out.write("                                    <div class=\"comment__item\">\r\n");
      out.write("                                        <div class=\"comment__item__question\">\r\n");
      out.write("                                            <span class=\"comment__text__avatar\">N</span>\r\n");
      out.write("                                            <span class=\"comment__item__name\">Nhi</span>\r\n");
      out.write("                                            <div class=\"comment__item__content\">Máy có bán trả góp không ạ?</div>\r\n");
      out.write("                                            <span class=\"comment__item__reply\">Trả lời</span>\r\n");
      out.write("                                            <span class=\"comment__item__time\">7 giờ trước</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"comment__reply\">\r\n");
      out.write("                                            <div class=\"comment__reply__contain\">\r\n");
      out.write("                                                <!-- Admin: .admin -->\r\n");
      out.write("                                                <div class=\"comment__reply__item admin\">\r\n");
      out.write("                                                    <span class=\"comment__text__avatar\">Q</span>\r\n");
      out.write("                                                    <span class=\"comment__item__name\">Hữu Qui</span>\r\n");
      out.write("                                                    <span class=\"comment__item__admin\">Quản trị viên</span>\r\n");
      out.write("                                                    <div class=\"comment__item__content\">\r\n");
      out.write("                                                        Dạ bên em có hỗ trợ bán trả góp ạ. <br>\r\n");
      out.write("                                                        Thông tin đến chị.\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <span class=\"comment__item__reply\">Trả lời</span>\r\n");
      out.write("                                                    <span class=\"comment__item__time\">7 giờ trước</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"comment__item\">\r\n");
      out.write("                                        <div class=\"comment__item__question\">\r\n");
      out.write("                                            <span class=\"comment__text__avatar\">N</span>\r\n");
      out.write("                                            <span class=\"comment__item__name\">Nhi</span>\r\n");
      out.write("                                            <div class=\"comment__item__content\">Máy có bán trả góp không ạ?</div>\r\n");
      out.write("                                            <span class=\"comment__item__reply\">Trả lời</span>\r\n");
      out.write("                                            <span class=\"comment__item__time\">7 giờ trước</span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"comment__reply\">\r\n");
      out.write("                                            <div class=\"comment__reply__contain\">\r\n");
      out.write("                                                <div class=\"comment__reply__item admin\">\r\n");
      out.write("                                                    <span class=\"comment__text__avatar\">Q</span>\r\n");
      out.write("                                                    <span class=\"comment__item__name\">Hữu Qui</span>\r\n");
      out.write("                                                    <span class=\"comment__item__admin\">Quản trị viên</span>\r\n");
      out.write("                                                    <div class=\"comment__item__content\">\r\n");
      out.write("                                                        Dạ bên em có hỗ trợ bán trả góp ạ. <br>\r\n");
      out.write("                                                        Thông tin đến chị.\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <span class=\"comment__item__reply\">Trả lời</span>\r\n");
      out.write("                                                    <span class=\"comment__item__time\">7 giờ trước</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"comment__reply__item\">\r\n");
      out.write("                                                    <span class=\"comment__text__avatar\">N</span>\r\n");
      out.write("                                                    <span class=\"comment__item__name\">Nhi</span>\r\n");
      out.write("                                                    <span class=\"comment__item__admin\">Quản trị viên</span>\r\n");
      out.write("                                                    <div class=\"comment__item__content\">\r\n");
      out.write("                                                        Ok, cám ơn em.\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <span class=\"comment__item__reply\">Trả lời</span>\r\n");
      out.write("                                                    <span class=\"comment__item__time\">7 giờ trước</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"comment__pagination\">\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col p-6 t-8 m-12\">\r\n");
      out.write("                                            <ul class=\"comment__pagination__list\">\r\n");
      out.write("                                                <li class=\"comment__pagination__item\">\r\n");
      out.write("                                                    <a href=\"#\"><<</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Active: .active -->\r\n");
      out.write("                                                <li class=\"comment__pagination__item active\">\r\n");
      out.write("                                                    <a href=\"#\">1</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("\r\n");
      out.write("                                                <li class=\"comment__pagination__item\">\r\n");
      out.write("                                                    <a href=\"#\">2</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("\r\n");
      out.write("                                                <li class=\"comment__pagination__item\">\r\n");
      out.write("                                                    <a href=\"#\">3</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("\r\n");
      out.write("                                                <li class=\"comment__pagination__item\">\r\n");
      out.write("                                                    <a href=\"#\">...</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("\r\n");
      out.write("                                                <li class=\"comment__pagination__item\">\r\n");
      out.write("                                                    <a href=\"#\">20</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("\r\n");
      out.write("                                                <li class=\"comment__pagination__item\">\r\n");
      out.write("                                                    <a href=\"#\">>></a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("        	</div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- end .body -->\r\n");
      out.write("        <!-- Active: .active -->\r\n");
      out.write("	    <div class=\"overload\"></div>\r\n");
      out.write("		<!-- Javascript -->\r\n");
      out.write("		<script>\r\n");
      out.write("			var idProduct = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("		</script>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f11(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("		<script type=\"text/javascript\" src=\"");
      if (_jspx_meth_c_005furl_005f12(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("		<script type=\"text/javascript\">header(true);</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /views/web/jsp/productDetail.jsp(9,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/views/web/css/productDetail.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /views/web/jsp/productDetail.jsp(44,76) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/views/source/image/product/pd04.png");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /views/web/jsp/productDetail.jsp(45,64) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/views/source/image/product/pd03.png");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /views/web/jsp/productDetail.jsp(46,64) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/views/source/image/product/dt02.jpg");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f4_reused = false;
    try {
      _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f4.setParent(null);
      // /views/web/jsp/productDetail.jsp(117,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f4.setValue("/views/source/image/product/dt02.jpg");
      int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
      if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      _jspx_th_c_005furl_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f4, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f5_reused = false;
    try {
      _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f5.setParent(null);
      // /views/web/jsp/productDetail.jsp(126,46) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f5.setValue("/views/source/image/product/dt01.jpg");
      int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
      if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      _jspx_th_c_005furl_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f5, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f6_reused = false;
    try {
      _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f6.setParent(null);
      // /views/web/jsp/productDetail.jsp(404,66) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f6.setValue("/views/source/image/product/pd04.png");
      int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
      if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      _jspx_th_c_005furl_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f6, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f7 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f7_reused = false;
    try {
      _jspx_th_c_005furl_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f7.setParent(null);
      // /views/web/jsp/productDetail.jsp(427,78) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f7.setValue("/views/source/image/product/pd10.png");
      int _jspx_eval_c_005furl_005f7 = _jspx_th_c_005furl_005f7.doStartTag();
      if (_jspx_th_c_005furl_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f7);
      _jspx_th_c_005furl_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f7, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f8 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f8_reused = false;
    try {
      _jspx_th_c_005furl_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f8.setParent(null);
      // /views/web/jsp/productDetail.jsp(450,78) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f8.setValue("/views/source/image/product/pd07.png");
      int _jspx_eval_c_005furl_005f8 = _jspx_th_c_005furl_005f8.doStartTag();
      if (_jspx_th_c_005furl_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f8);
      _jspx_th_c_005furl_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f8, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f9 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f9_reused = false;
    try {
      _jspx_th_c_005furl_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f9.setParent(null);
      // /views/web/jsp/productDetail.jsp(473,78) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f9.setValue("/views/source/image/product/pd02.png");
      int _jspx_eval_c_005furl_005f9 = _jspx_th_c_005furl_005f9.doStartTag();
      if (_jspx_th_c_005furl_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f9);
      _jspx_th_c_005furl_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f9, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f10 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f10_reused = false;
    try {
      _jspx_th_c_005furl_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f10.setParent(null);
      // /views/web/jsp/productDetail.jsp(496,78) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f10.setValue("/views/source/image/product/pd06.png");
      int _jspx_eval_c_005furl_005f10 = _jspx_th_c_005furl_005f10.doStartTag();
      if (_jspx_th_c_005furl_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f10);
      _jspx_th_c_005furl_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f10, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f11 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f11_reused = false;
    try {
      _jspx_th_c_005furl_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f11.setParent(null);
      // /views/web/jsp/productDetail.jsp(686,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f11.setValue("/views/web/js/header.js");
      int _jspx_eval_c_005furl_005f11 = _jspx_th_c_005furl_005f11.doStartTag();
      if (_jspx_th_c_005furl_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f11);
      _jspx_th_c_005furl_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f11, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f12 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f12_reused = false;
    try {
      _jspx_th_c_005furl_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f12.setParent(null);
      // /views/web/jsp/productDetail.jsp(687,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f12.setValue("/views/web/js/productDetail.js");
      int _jspx_eval_c_005furl_005f12 = _jspx_th_c_005furl_005f12.doStartTag();
      if (_jspx_th_c_005furl_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f12);
      _jspx_th_c_005furl_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f12, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f12_reused);
    }
    return false;
  }
}
